spring:
  application:
    name: HSA-Config-Server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/siddheshm67/AHS-Config-properties.git
          clone-on-start: true    
    
server:
  port: 9091  
  
  
    
