server:
  port: 2222
  
spring:
  application:
    name: GREET-API

  boot:
    admin:
      client:
        url: http://localhost:9090/
        
managment:
  endpoints:
    web:
      exposure:
        include: '*'    