server:
  port: 8081
  
spring:
  application:
    name: HSA-PLAN-API
    
  datasource:
    password: root
    url: jdbc:mysql://127.0.0.1:3306/hsa_db
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mail:
    host: smtp.gmail.com
    password: "strk fztz sveb xipx"
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    username: siddheshmadiwale@gmail.com
    
  boot:
    admin:
      client:
        url: http://localhost:9090/
    
managemnet:
  endpoints:
    web:
      exposure:
        include:'*'
